### ISSUE TITLE
Comments before a kpt-template directive cause the template to not be expanded

### ISSUE THREAD

**Issue by Niksko** [seek-oss/kpt-functions#14]
Non-working version:
```
# Some sort of comment
# {"$kpt-template":"true"}
foobar: |
  {{render "some-template"}}
```

After syncing, the above appears unchanged

Working version:
```
# Some sort of comment
                                          <-- whitespace
# {"$kpt-template":"true"}
foobar: |
  {{render "some-template"}}
```

After syncing, the template is correctly rendered. However the comment is now below the rendered template? Something funky going on here with the template rendering.

**Comment by mper0003** [comment]
Comments at the top of a resource doesn't keep it's original position after syncing.
### Example 1:
Package:
```yaml
# Some comment
apiVersion: v1 
kind: Namespace
....
```
After syncing the comment is on the side:
```yaml
apiVersion: v1 # Some comment
kind: Namespace
....
```
### Example 2:
Also, package:
```yaml
# Some comment with whitespace before resource

apiVersion: v1
kind: Namespace
...
```
After syncing the comment is removed:
```yaml
apiVersion: v1
kind: Namespace
...
```
